### ISSUE TITLE
Moving this repo under dmwm/cms-htcondor-es

### ISSUE THREAD

**Issue by mrceyhun** [cronosnull/CMS-Monit-notifier#1]
Hi @cronosnull , hope you are well and good :) 

For ease of management, can we move this repo under a directory of dmwm/cms-htcondor-es? I did not copy and paste your code because of ownership. If you open a PR, I can merge and update it with the local changes.

Thanks in advance!

fyi @leggerf

**Comment by cronosnull** [comment]
Hi  @mrceyhun! 

Please go ahead and add the folder :) no need to keep the history (maybe you will want to take a look at the branches as I think there are useful changes not merged into the master). 

Cheers.

**Comment by mrceyhun** [comment]
Thanks @cronosnull !!
